### ISSUE TITLE
DI полей

### ISSUE THREAD

**Issue by das13** [ValentynChepiha/NCProjectEShopClient#10]
В Spring не рекомендуется использовать DI полей:
CheckBeforeLoad
CurrencyExchangeRepository
CurrencyRateRepository
DCurrencyRepository
EndpointBasketDonePostService
EndpointBasketPostService
LoadExchangeService
LoadGoodsService
LoadXMLService
MainController
ParseBasketDataValue

**Comment by ValentynChepiha** [comment]
done c5a5c899e784221ce2b7b69149812a3838131332
