### ISSUE TITLE
Правильный DI

### ISSUE THREAD

**Issue by das13** [ValentynChepiha/NCProjectEShopClient#7]
При DI необходимо использовать Интерфейс, а не класс. Т.е.
в
```
@Autowired
private EndpointBasketDonePostService endpointBasketDonePostService;
```
EndpointBasketDonePostService д.б. интерфейс, а его реализация - EndpointBasketDonePostServiceImpl (например)
В IDEA для этого можно использовать Refactor -> Extract Interface

**Comment by ValentynChepiha** [comment]
Done c5a5c899e784221ce2b7b69149812a3838131332
